/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicLoginRouteRouteImport } from './routes/(public)/login/route'
import { Route as publicLoginIndexRouteImport } from './routes/(public)/login/index'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRouteRoute = publicLoginRouteRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginIndexRoute = publicLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicLoginRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof publicLoginRouteRouteWithChildren
  '/': typeof publicIndexRoute
  '/login/': typeof publicLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/login': typeof publicLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRoute
  '/(public)/login': typeof publicLoginRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(public)/login/': typeof publicLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login'
  id:
    | '__root__'
    | '/(protected)'
    | '/(public)/login'
    | '/(public)/'
    | '/(public)/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRoute
  publicLoginRouteRoute: typeof publicLoginRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login/': {
      id: '/(public)/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof publicLoginIndexRouteImport
      parentRoute: typeof publicLoginRouteRoute
    }
  }
}

interface publicLoginRouteRouteChildren {
  publicLoginIndexRoute: typeof publicLoginIndexRoute
}

const publicLoginRouteRouteChildren: publicLoginRouteRouteChildren = {
  publicLoginIndexRoute: publicLoginIndexRoute,
}

const publicLoginRouteRouteWithChildren =
  publicLoginRouteRoute._addFileChildren(publicLoginRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRoute,
  publicLoginRouteRoute: publicLoginRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
